### ISSUE TITLE
lab01 .gitignore

### ISSUE THREAD

**Issue by samuelbarata** [pedromigueladao/IAED1819#1]
O `.gitignore` do lab01 devia incluir os nomes dos ficheiros que vão ser criados e das suas compilações: 

```gitignore
ex01.c
ex01
ex02.c
ex02
```

**Comment by MikolasJanota** [comment]
Sim, deveria. Esteja a vontade de os adicionar.

A estrutura das pastas ainda temos que refinar. No lab02 já está mais
organizado, mas sugestões são bem vindas.

-M
