### ISSUE TITLE
llegal byte sequence

### ISSUE THREAD

**Issue by rodref98** [pedromigueladao/IAED1819#2]
Ao correr os testes do lab2, os meus programas passam em todos os testes mas ao correr o script aparece a mensagem "llegal byte sequence" 
Não impede de correr os testes e não afeta em nada tudo o resto
Só não percebo o porque de aparecer essa mensagem

exemplo: 
"Test: tests/ex02_2.in
tr: Illegal byte sequence
Program successfully ran...
Test tests/ex02_2.in PASSED!"

**Comment by MikolasJanota** [comment]
Estas no mac? Parece que o tr esta implementado duma maneira estranha la.
Alterei. Pff verifica

**Comment by rodref98** [comment]
Obrigado pela rapida resposta professor
O problema esta resolvido obrigado

Cumprimentos,
Rodrigo Fernandes

No dia 27/02/2019, às 12:28, MikolasJanota <notifications@github.com<mailto:notifications@github.com>> escreveu:

Estas no mac? Parece que o tr esta implementado duma maneira estranha la.
Alterei. Pff verifica
