### ISSUE TITLE
Lab04 '\n' char em falta nos ex05 ex06

### ISSUE THREAD

**Issue by Jonyleo** [pedromigueladao/IAED1819#3]
Estes testes falham sempre por mais que mude o codigo apesar de que quando testo o programa no terminal funciona.
Quando corri o programa com o ex05_0.in obtive segmentation fault porque o meu codigo espera por '\n' como diz no enunciado para parar de pedir caracteres, como nunca vem, acaba por passar VECMAX. Ao por um "enter" no ficheiro .in já passou esse teste.

Outra possivel solução é mudar o enunciado para dizer "até encontrar um '\n' ou EOF".

ENUNCIADO ex05:
"até encontrar o carácter `\n`"

ENUNCIADO ex06:
"use a função do exercício anterior"
sendo que é a mesma função tem o mesmo erro pois não recebe nenhum '\n'

**Comment by MikolasJanota** [comment]
Geralmente é boa prática esperar EOF, mas tens razão, alterei o enunciado.
