### ISSUE TITLE
[Lab05] [Ex01] [Output] Enunciado não corresponde ao esperado pelos testes

### ISSUE THREAD

**Issue by Jonyleo** [pedromigueladao/IAED1819#4]
De acordo com as passagens do enunciado:
```
Implemente um programa que calcule a disciplina mais popular (na média) e o aluno que na média mais gosta de estudar.
``` 
e
```
O resultado deve ser impresso com a disciplina mais popular na primeira linha e o aluno mais entusiástico na segunda linha.
```
O esperado é o output ser simplesmente um numero de disciplina e um de aluno. No entanto os testes esperam tambem os trios de A,D,V que não parece ser diretamente pedido no enunciado.
![image](https://user-images.githubusercontent.com/45317302/54538694-9aa0f680-498c-11e9-97a1-f7eab56c65fe.png)
*Ex01_0.out*

**Comment by MikolasJanota** [comment]
tens razao, fix nos testes pushed
